# Project Euler

1. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

In [61]:
a = range(1,1000)
b = range(1,10)

In [62]:
y = []
def multiples (x):
    for i in x:
        if i%5==0:
            y.append(i)
        elif i%3==0:
            y.append(i)
        else: 
            y.append(0)   
    return sum(y)

In [148]:
print('The answer is:')
multiples(a)

The answer is:

466336

2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [48]:
out = [1,2]
for i in range(2, 50):
    add=out[i-2]+out[i-1]
    out.append(add)

In [49]:
out2 = []
for j in out:
    if j<=4000000:
        out2.append(j)

In [51]:
result = 0
for k in out2:
    if k%2==0:
        result=result+k

In [149]:
print('The answer is:')
result

The answer is:

4613732

3. The prime factors of 13195 are 5, 7, 13 and 29.

   What is the largest prime factor of the number 600851475143 ?

In [139]:
def largestprimefactor(x):
    out = []
    for i in range(2,100000000000001):
        if x%i==0:
            x=x/i
            out.append(i)
    return out

In [150]:
print('The answer is:')
max(largestprimefactor(600851475143))

The answer is:

6857

4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit    numbers is 9009 = 91 Ã— 99.
   Find the largest palindrome made from the product of two 3-digit numbers.

In [254]:
import itertools
def palindrome(x,y):
    out = []
    for i, j in itertools.product(x,y):
        k = i*j
        if k>100000:
            if (str(k)[0]==str(k)[5]) & (str(k)[1]==str(k)[4]) & (str(k)[2]==str(k)[3]):
                #print(i,j)
                out.append(k)
    return max(out)

In [255]:
m = range(100, 1000)
n = range(100,1000)

print('The answer is:')
palindrome(m,n)

The answer is:

906609

5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [292]:
def SmallestMultiple(x):
    for i in x:
        if (i%10==0) & (i%11==0) & (i%13==0) & (i%14==0) & (i%15==0) & (i%16==0)\
         & (i%17==0) & (i%18==0) & (i%19==0):
            return i

In [293]:
a = range(10000,33522128641)

SmallestMultiple(a)

232792560

6. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [300]:
n = range(1,101)
s1=sum(n)**2
s2 = 0
for i in n:
    s2=s2+i**2

In [302]:
print('The answer is:')
s1-s2

The answer is:

25164150

7. By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

    What is the 10 001st prime number?

In [52]:
n = range(2,1000000)

In [53]:
prime = []
for i in n:
    for j in range(2,i):
        if (i%j)==0:
            break
    else:
        prime.append(i)

In [56]:
print('The answer is:')
prime[10000]

The answer is:

104743

9. A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

    \begin{equation}

    a^2 + b^2 = c^2
    
    For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.
       
    There exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc.

In [35]:
import itertools

a = range(100,1000)
b = range(100,1000)
c = range(100,1000)

for i,j,k in itertools.product(a,b,c):
     if (i**2+j**2==k**2) & (i+j+k==1000):
        print(i,j,k)

200 375 425
375 200 425

In [37]:
print('The anser is:')
200*375*425

The anser is:

31875000